### ISSUE TITLE
Twitter Developer Account

### ISSUE THREAD

**Issue by jasonrwang** [yasuiniko/LetsTalkBell#1]
I don't have a Twitter Developer Account 
# ¯\_(ツ)_/¯

**Comment by yasuiniko** [comment]
Twitter dev accounts are twitter accounts. To activate your account, go [here](https://dev.twitter.com/), and to make an app go [here](https://apps.twitter.com/).

**Comment by jasonrwang** [comment]
One day I will be almighty like you, @yasuiniko.
